// MK4 — Browser storage adapter + dev-server log sink. Platform glue only:
// no game rules live here. The logic layer produces serialized saves and log
// entries; this module persists them (localStorage) and, in dev, mirrors log
// entries to the Vite middleware sink so they land in a text file on the dev
// machine — including entries generated by a phone playing over the LAN.

import { MAX_METRIC_LOG_ENTRIES, MAX_TURN_LOG_ENTRIES, MetricLogEntry, TurnLogEntry } from './logic/logger';

const SAVE_KEY = 'breach:save';
const METRICS_LOG_KEY = 'breach:log:metrics';
const TURN_LOG_KEY = 'breach:log:turns';

function readArray<T>(key: string): T[] {
  try {
    const raw = localStorage.getItem(key);
    const arr = raw ? (JSON.parse(raw) as T[]) : [];
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

function writeArray<T>(key: string, arr: T[], cap: number): void {
  const trimmed = arr.length > cap ? arr.slice(arr.length - cap) : arr;
  try {
    localStorage.setItem(key, JSON.stringify(trimmed));
  } catch {
    // quota pressure: drop the older half and retry once, else give up quietly
    try {
      localStorage.setItem(key, JSON.stringify(trimmed.slice(Math.floor(trimmed.length / 2))));
    } catch {
      /* logging must never break the game */
    }
  }
}

// ---- MK4.1 save/restore ----

export function saveBattle(json: string, turn: number): void {
  try {
    localStorage.setItem(SAVE_KEY, json);
    console.info(`[breach] state saved (turn ${turn})`);
  } catch (e) {
    console.warn('[breach] autosave failed', e);
  }
}

export function loadBattleJson(): string | null {
  try {
    return localStorage.getItem(SAVE_KEY);
  } catch {
    return null;
  }
}

export function clearBattleSave(): void {
  try {
    localStorage.removeItem(SAVE_KEY);
  } catch {
    /* ignore */
  }
}

// ---- MK4.3 log persistence ----

function postToSink(kind: 'metrics' | 'turn', entry: unknown): void {
  if (!import.meta.env.DEV) return; // dev-server sink only exists under `npm run dev`
  void fetch('/__breach/log', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ kind, at: new Date().toISOString(), entry }),
  }).catch(() => {
    /* sink unreachable (e.g. preview build) — localStorage still has the logs */
  });
}

export function appendMetricsLog(entry: MetricLogEntry): void {
  const arr = readArray<MetricLogEntry>(METRICS_LOG_KEY);
  arr.push(entry);
  writeArray(METRICS_LOG_KEY, arr, MAX_METRIC_LOG_ENTRIES);
  postToSink('metrics', entry);
}

export function appendTurnLogs(entries: TurnLogEntry[]): void {
  if (!entries.length) return;
  const arr = readArray<TurnLogEntry>(TURN_LOG_KEY);
  arr.push(...entries);
  writeArray(TURN_LOG_KEY, arr, MAX_TURN_LOG_ENTRIES);
  for (const e of entries) postToSink('turn', e);
}

export function readLogs(): { metrics: MetricLogEntry[]; turns: TurnLogEntry[] } {
  return { metrics: readArray(METRICS_LOG_KEY), turns: readArray(TURN_LOG_KEY) };
}

export function wipeLogs(): void {
  try {
    localStorage.removeItem(METRICS_LOG_KEY);
    localStorage.removeItem(TURN_LOG_KEY);
  } catch {
    /* ignore */
  }
}
