// MK4 — Browser storage adapter + dev-server log sink. Platform glue only:
// no game rules live here. The logic layer produces serialized saves and log
// entries; this module persists them (localStorage) and, in dev, mirrors log
// entries to the Vite middleware sink so they land in a text file on the dev
// machine — including entries generated by a phone playing over the LAN.

import { COLOR_COUNT, DEFAULT_BATTLE_CONFIG, SHAPE_COUNT } from './logic/constants';
import { MAX_METRIC_LOG_ENTRIES, MAX_TURN_LOG_ENTRIES, MetricLogEntry, TurnLogEntry } from './logic/logger';
import { isValidStrongRecord } from './logic/save';
import { BattleConfig, Color, Shape, Side } from './logic/types';

const SAVE_KEY = 'breach:save';
const METRICS_LOG_KEY = 'breach:log:metrics';
const TURN_LOG_KEY = 'breach:log:turns';
const CONFIG_KEY = 'breach:config';

function readArray<T>(key: string): T[] {
  try {
    const raw = localStorage.getItem(key);
    const arr = raw ? (JSON.parse(raw) as T[]) : [];
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

function writeArray<T>(key: string, arr: T[], cap: number): void {
  const trimmed = arr.length > cap ? arr.slice(arr.length - cap) : arr;
  try {
    localStorage.setItem(key, JSON.stringify(trimmed));
  } catch {
    // quota pressure: drop the older half and retry once, else give up quietly
    try {
      localStorage.setItem(key, JSON.stringify(trimmed.slice(Math.floor(trimmed.length / 2))));
    } catch {
      /* logging must never break the game */
    }
  }
}

// ---- MK4.1 save/restore ----

export function saveBattle(json: string, turn: number): void {
  try {
    localStorage.setItem(SAVE_KEY, json);
    console.info(`[breach] state saved (turn ${turn})`);
  } catch (e) {
    console.warn('[breach] autosave failed', e);
  }
}

export function loadBattleJson(): string | null {
  try {
    return localStorage.getItem(SAVE_KEY);
  } catch {
    return null;
  }
}

export function clearBattleSave(): void {
  try {
    localStorage.removeItem(SAVE_KEY);
  } catch {
    /* ignore */
  }
}

// ---- MK5.4 menu-config persistence (persists across sessions; nothing
// resets it implicitly — "Reset to Defaults" in the UI is the only reset) ----

// Alpha 0.1.0 (cfgV 4): the flat-cost and per-ability-cost fields are REMOVED
// from BattleConfig (§4.3-4.5). Obsolete persisted cost settings from earlier
// builds are ignored without crashing — the migration simply does not copy
// them; every surviving field is preserved. Pre-MK8 stampless configs and
// missing strong bindings migrate as before.
const MENU_CONFIG_VERSION = 4;

function cloneStrong<T extends Color | Shape>(r: Record<Side, T[]>): Record<Side, T[]> {
  return { player: [...r.player], enemy: [...r.enemy] };
}

export function loadMenuConfig(): BattleConfig {
  try {
    const raw = localStorage.getItem(CONFIG_KEY);
    if (!raw) return { ...DEFAULT_BATTLE_CONFIG };
    const c = JSON.parse(raw) as BattleConfig & { cfgV?: number };
    if (
      typeof c.enemyMatching !== 'boolean' ||
      typeof c.hackerBonusEnabled !== 'boolean' ||
      typeof c.singleAxisPayout !== 'boolean' ||
      typeof c.noMatchDamage !== 'boolean' ||
      !(c.maxCascadeSteps === null || (Number.isInteger(c.maxCascadeSteps) && c.maxCascadeSteps >= 0 && c.maxCascadeSteps <= 9)) ||
      !(Number.isInteger(c.playerHp) && c.playerHp >= 1 && c.playerHp <= 9999) ||
      !(Number.isInteger(c.enemyHp) && c.enemyHp >= 1 && c.enemyHp <= 9999) ||
      typeof c.hintEnabled !== 'boolean' ||
      typeof c.nmdChargeAwareBot !== 'boolean' ||
      !(Number.isInteger(c.hintDelaySeconds) && c.hintDelaySeconds >= 1 && c.hintDelaySeconds <= 60)
    ) {
      return { ...DEFAULT_BATTLE_CONFIG };
    }
    const cfg: BattleConfig = {
      enemyMatching: c.enemyMatching,
      hackerBonusEnabled: c.hackerBonusEnabled,
      singleAxisPayout: c.singleAxisPayout,
      maxCascadeSteps: c.maxCascadeSteps,
      noMatchDamage: c.noMatchDamage,
      playerHp: c.playerHp,
      enemyHp: c.enemyHp,
      hintEnabled: c.hintEnabled,
      hintDelaySeconds: c.hintDelaySeconds,
      nmdChargeAwareBot: c.nmdChargeAwareBot,
      // MK9.4: use stored strong bindings when well-formed; otherwise fill from
      // defaults (migration for older configs that predate them).
      strongColors: isValidStrongRecord(c.strongColors, COLOR_COUNT)
        ? cloneStrong(c.strongColors)
        : cloneStrong(DEFAULT_BATTLE_CONFIG.strongColors),
      strongShapes: isValidStrongRecord(c.strongShapes, SHAPE_COUNT)
        ? cloneStrong(c.strongShapes)
        : cloneStrong(DEFAULT_BATTLE_CONFIG.strongShapes),
    };
    if (c.cfgV === undefined) {
      // pre-MK8 config (never stamped): adopt the MK8.3 defaults for the fields
      // whose defaults changed then. Post-MK8 configs keep their own.
      cfg.playerHp = DEFAULT_BATTLE_CONFIG.playerHp;
      cfg.enemyHp = DEFAULT_BATTLE_CONFIG.enemyHp;
    }
    if (c.cfgV !== MENU_CONFIG_VERSION) {
      // Alpha migration: obsolete cost fields (if present) are dropped by the
      // explicit field copy above; re-stamp so migration never re-runs.
      saveMenuConfig(cfg);
    }
    return cfg;
  } catch {
    return { ...DEFAULT_BATTLE_CONFIG };
  }
}

export function saveMenuConfig(c: BattleConfig): void {
  try {
    localStorage.setItem(CONFIG_KEY, JSON.stringify({ ...c, cfgV: MENU_CONFIG_VERSION }));
  } catch {
    /* ignore */
  }
}

// ---- MK4.3 log persistence ----

function postToSink(kind: 'metrics' | 'turn', entry: unknown): void {
  // dev-server sink only exists under `npm run dev`; guarded so non-Vite
  // runtimes (tests) can import this module safely
  if (!(import.meta as { env?: { DEV?: boolean } }).env?.DEV) return;
  void fetch('/__breach/log', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ kind, at: new Date().toISOString(), entry }),
  }).catch(() => {
    /* sink unreachable (e.g. preview build) — localStorage still has the logs */
  });
}

export function appendMetricsLog(entry: MetricLogEntry): void {
  const arr = readArray<MetricLogEntry>(METRICS_LOG_KEY);
  arr.push(entry);
  writeArray(METRICS_LOG_KEY, arr, MAX_METRIC_LOG_ENTRIES);
  postToSink('metrics', entry);
}

export function appendTurnLogs(entries: TurnLogEntry[]): void {
  if (!entries.length) return;
  const arr = readArray<TurnLogEntry>(TURN_LOG_KEY);
  arr.push(...entries);
  writeArray(TURN_LOG_KEY, arr, MAX_TURN_LOG_ENTRIES);
  for (const e of entries) postToSink('turn', e);
}

export function readLogs(): { metrics: MetricLogEntry[]; turns: TurnLogEntry[] } {
  return { metrics: readArray(METRICS_LOG_KEY), turns: readArray(TURN_LOG_KEY) };
}

export function wipeLogs(): void {
  try {
    localStorage.removeItem(METRICS_LOG_KEY);
    localStorage.removeItem(TURN_LOG_KEY);
  } catch {
    /* ignore */
  }
}
